### PR TITLE
fix typo in programID

### PR DESCRIPTION
**Pull request by emilylittle**
https://app.asana.com/0/1201647585774820/1206314972825351/f

Fix typo 😄 

image

[docs](https://developer.amazon.com/docs/incentives-api/digital-gift-cards.html#requests)

also curious the reasons were that led us to forking if anyone has background!

### CODE REVIEW

**Review by jules27 — APPROVED** [review]
Is this new code? Should there be corresponding tests for this?

**Review by victor-tremendous — APPROVED** [review]
Sorry, no idea about the reason for the fork, I didn't even know it existed until now 😅

**Comment by emilylittle** [comment]
> Is this new code? Should there be corresponding tests for this?

no this is old code, I just noticed we weren't using the correct key here.

all the specs in this repo are commented out, so I figured it wasn't worth the time to try to get the test suite running. i feel like finding a maintained gem we can use may be a better approach (assuming the reason for this fork is no longer valid)

**Comment by jules27** [comment]
omg I just noticed this PR is not in core lol

**Comment by jules27** [comment]
Thanks for the fix!

**Pull request merged**
